spring:
  jpa:
    show-sql: false
  properties:
    hibernate:
      format_sql: false
  h2:
    console:
      enabled: false
pitanga:
  room:
    min-id: 10000000
    max-id: 99999999
    max-rooms: 4
    max-users: 4
  web-socket:
    paths:
      - pitanga
    allowed-origins:
      - http://pitanga.figtreelake.com
      - https://pitanga.figtreelake.com
      - http://marceloleite2604.github.io
      - https://marceloleite2604.github.io
  user:
    max-users: 4
    icons:
      - â˜•
      - ğŸ—
      - â­
      - ğŸ€
